title: Remote Sensing and Spatial Analysis Portfolio for Michael Dear
logo: /img/mdear_profile_pic_round_800x800.png
description: These are some examples of my work in remote sensing and spatial analysis. 
#show_downloads: true
theme: jekyll-theme-minimal
